title: Nonlinearsound Blog
email: nonlinearsound@icloud.com
description: A small blog about my experiences in It and programming
github_username: nonlinearsound
url: https://nonlinearsound.github.io
baseurl: /blog
theme: minima
plugins:
 - jekyll-feed
